.\" Manpage for aftp-server
.\" Contact arthurzam@gmail.com to correct errors or typos.
.TH man 1 "18 Jul 2014" "1.0" "aftp-server man page"
.SH NAME
aftp-server \- Very fast file transfering server
.SH SYNOPSIS
aftp-server (-p [port]) (-f [path]) (-db [path]) (-a)
.TP
aftp-server -h
.SH DESCRIPTION
.B aftp-server
is a very fast file transfering server, using UDP transport layer. This server is built with purpose for security and fast transfer. The protocol is stateful, meaning the server saves client's connection data until the connection is closed or timed-out.
.PP
.TP
.B \-a
After loading all other arguments, start listening on the selected port. If you see that the program shows that the server isn't running, then error happened that didn't enable the starting. As default the server doesn't start.
.TP
.B \-p [port]
Use the specific port instead of the default one (7777). The port number must be valid, and if it isn't, the argument would be ignored. If the port is in use, the server would not be able to start!
.TP
.B \-db [path]
Load the database for logins from the specific path. Files format should be exactly as the one the program saves. In a bad format undefined behave might happen.
.TP
.B \-f [path]
The base folder path for the server root folder. Into this folder all the connecting users will have access (if they have permissions for it). Please check that the user that runs the application has access of read write to the folder.The default one is "/opt/server/".
.TP
.B \-h
Show basic help message.
.PP

.SH Examples
.PP
.TP
.B aftp_server
All the configurations are the default once. The server doesn't auto start.
.TP
.B aftp_server -f ~ -p 666 -a
The server would use user's home directory as it's base folder, will listen on port 666. When all the configurations are loaded the server starts listening. Please note that a user still can't perform actions because no one can login (login database is empty).
.TP
.B aftp_server -db /opt/aftp_server.db
Load the database for logins from "/opt/aftp_server.db". The server doesn't auto start.
.PP

.SH BUGS
No known bugs. But if you find one, please send me an e-mail.
.SH AUTHOR
Arthur Zamarin (arthurzam@gmail.com)
.SH COPYRIGHT
Copyright (C) 2014 Arthur Zamarin <arthurzam@gmail.com>.